




.build/gertduino328/src/src.cpp : src/src.ino
	@mkdir -p .build/gertduino328/src
	@echo [93msrc/src.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/gertduino328/src/src.cpp
	@true

